### ISSUE TITLE
[BUG] Nostr NIP-5 extension Issues

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/nostrnip5#11]
**Describe the bug**

1. Paid Local Part registrations aren't being activated if paid for by a remote LNbits node:

e.g. 
from:
![image](https://user-images.githubusercontent.com/388061/212248541-a3a3ba45-332a-4325-850f-56efe30dd104.png)
to
![image](https://user-images.githubusercontent.com/388061/212246542-e4048491-8819-4f33-84b4-497552be20ad.png)

And **Success! Your username is now active at crazynoisybizarretown@nostriches.verifiableclaims.nz. Please add this to your nostr profile accordingly. If you ever need to rotate your keys, you can still keep your identity!**

but crazynoisybizarretown (ID `KkD479tGBVg9HZFaErbbRn`) isn't active:
![image](https://user-images.githubusercontent.com/388061/212246571-4709b737-106d-4513-ab43-235fd3228eeb.png)

But there is no such problem if paid from an account in the same `usr`.

2. When using the active NIP-5 validation **Failed to verify NIP05 identifier on server** is the result.

https://nostriches.verifiableclaims.nz/.well-known/nostr.json?name=crazynoisybizarretown

**Expected behavior**
1. That wherever the payment was made, if successful the NIP-05 would be active.
2. That the NIP-05 would be accepted by Nostr clients.

**Desktop (please complete the following information):**
 - LNbits version: aafd955bb42c5affd032f5b296e6f9dec4d4dd31
 - Database: sqlite

**Additional context**
I would love a NIP-05 server validator.

**Comment by talvasconcelos** [comment]
I think this might be a listeners issue! Is the issue still present? Does it happen if you try a payment on a freshly booted lnbits?

**Comment by dni** [comment]
is this related to lnurlp extension? https://github.com/lnbits/lnurlp

**Comment by motorina0** [comment]
Transferred issue this repo.
The issue is fixed, but I will close it after the next release is out.

**Comment by S7NC** [comment]
> Transferred issue this repo. The issue is fixed, but I will close it after the next release is out.

Just did a test of 2.6, issue still seems to persist, after payment the nip-05 is still active false

**Comment by motorina0** [comment]
There might be an issue with extension upgrade. Can you please restart your LNbits instance.

I have re-tested and it works as expected.

Do you have any errors in the logs?

**Comment by S7NC** [comment]
i'll try a fresh instance, might be the upgrades, also thanks for these upgrades this extension is becoming serious 🔥

**Comment by S7NC** [comment]
Ran a fresh 12.10 copy, set with Alby wallet

`2024-08-08 12:49:33.74 | INFO | 172.17.0.1:62910 - "GET /nostrnip5/api/v1/domain/kpEf4e3CfaAsCoE4hzpiAb/payments/cec017fbc8f6f748d21a07211f259d3abddb143a80ab91a492a0bf158b527774 HTTP/1.1" 200
2024-08-08 12:49:36.62 | DEBUG | Checking incoming pending payment cec017fbc8f6f748d21a07211f259d3abddb143a80ab91a492a0bf158b527774
2024-08-08 12:49:36.71 | DEBUG | Status: success
2024-08-08 12:49:36.72 | INFO | Marking 'in' cec017fbc8f6f748d21a07211f259d3abddb143a80ab91a492a0bf158b527774 as not pending anymore: success
2024-08-08 12:49:36.78 | INFO | 172.17.0.1:62910 - "GET /nostrnip5/api/v1/domain/kpEf4e3CfaAsCoE4hzpiAb/payments/cec017fbc8f6f748d21a07211f259d3abddb143a80ab91a492a0bf158b527774 HTTP/1.1" 200
2024-08-08 12:49:47.20 | INFO | 172.17.0.1:62914 - "GET /nostrnip5/ HTTP/1.1" 200
2024-08-08 12:49:47.36 | INFO | 172.17.0.1:62920 - "GET /nostrnip5/static/image/nostrnip5.png HTTP/1.1" 200
2024-08-08 12:49:47.38 | ERROR | Exception: No response returned.
2024-08-08 12:49:47.39 | ERROR | Exception in ASGI application`

Seems to be fine but after payment they still remains false, could it depend on the funding source ? 
I'll try to look into it a bit better in the next few days

**Comment by S7NC** [comment]
Forgot to give an update but all works as expected, was just expecting a full list to appear on the nostr.json route but seems that going through the name query works fine. Great work !
